name: update-blocklist
# This workflow updates the to-ipv4-blocklist.txt by running the main.py script daily at 2:30 AM UTC.

on:
  workflow_dispatch:
    inputs:
      reason:
          type: string
          description: Reason of triggering the workflow
          default: 'Testing'
  schedule:
  - cron: "01 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        cache: 'pip' # caching pip dependencies
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the Python script
      run: |
        python main.py
    - name: Update tor-ipv4-blocklist.txt
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Updates tor-ipv4-blocklist.txt file"
        git push
