name: Update-blocklist
# This workflow updates the to-ipv4-blocklist.txt by running the main.py script daily at 1:45 AM UTC.

on:
  workflow_dispatch:
    inputs:
      reason:
          type: string
          description: Reason of triggering the workflow
          default: 'Testing'
  schedule:
  - cron: "45 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        cache: 'pip' # caching pip dependencies
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the Python script
      run: |
        python main.py
    - name: Update tor-ipv4-blocklist.txt
      # https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update TOR IPv4 lists"
        file_pattern: "tor-ipv4-*.txt"
        branch: main
        author_name: "GitHub Actions"
